name: Build Raspberry Pi Kernel

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-kernel:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set Up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Kernel Docker Image
        run: |
          docker build --build-arg KERNEL_TAG=rpi-6.12.y_20241206_2 \
                       --build-arg ARCH=arm64 \
                       -t rpi-kernel:latest .

      - name: Extract Built Kernel Image
        run: |
          container_id=$(docker create rpi-kernel:latest)
          docker cp $container_id:/kernel.img ./kernel.img
          docker rm $container_id

      - name: Upload Kernel Image as Artifact
        uses: actions/upload-artifact@v3
        with:
          name: kernel-img
          path: ./kernel.img
